name: PR Check
on: [pull_request,push]

jobs:
  lint:
    name: Run static checks
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - uses: docker://docker.io/cilium/image-maker:60c02a5e6cb057f462739f2b7b19f5c3f6a22933
        name: Run make lint
        with:
          entrypoint: make
          args: lint
